name: "SSO Authentication"
guid: "505ce9d1-d916-42fa-86ca-673ef241d7df"
imageUrl: "https://raw.githubusercontent.com/9p4/jellyfin-plugin-sso/main/img/logo.png"
version: "3.4.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "9p4"
overview: "Authenticate users against an SSO provider."
description: |
  This plugin allows users to sign in through an SSO provider (such as Google, Facebook, or your own provider). This enables one-click signin.
  Review documentation at https://github.com/9p4/jellyfin-plugin-sso
category: "Authentication"
artifacts:
  - "SSO-Auth.dll"
  - "IdentityModel.OidcClient.dll"
  - "IdentityModel.dll"
changelog: |
  3.4.0.0: Add user self-service for linking existing accounts + managing existing links. Allow IDP accounts to be linked to jellyfin accounts with a different display-name.
  3.3.0.0: Add fallback authentication provider. Add OpenID admin page.
  3.2.0.0: Switch to hashmaps (BREAKING) for performance. Dump expected permissions in logs on error.
  3.1.0.1: Fix redirect bug in WebResponse (#7)
  3.1.0.0: Simplify auth flow so loading the web UI is not required
  3.0.0.0: Add more RBAC features and option to unregister user from SSO
  2.0.1.0: Fix improper artifact loading
  2.0.0.0: Add RBAC and Google support
  1.0.0.0: Initial Release
