name: "SSO Authentication"
guid: "505ce9d1-d916-42fa-86ca-673ef241d7df"
imageUrl: "https://raw.githubusercontent.com/sambhavsaggi/jellyfin-plugin-sso/main/img/logo.png"
version: "1"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "sambhavsaggi"
overview: "Authenticate users against an SSO provider"
description: This plugin allows users to sign in through an SSO provider (such as Google, Facebook, or your own provider). This enables one-click signin.
category: "Authentication"
artifacts:
  - "SSO-Auth.dll"
  - "IdentityModel.OidcClient.dll"
changelog: "2022-01-16: Initial Release"
