name: "SSO Authentication"
guid: "505ce9d1-d916-42fa-86ca-673ef241d7df"
imageUrl: "https://raw.githubusercontent.com/9p4/jellyfin-plugin-sso/main/img/logo.png"
version: "3.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "9p4"
overview: "Authenticate users against an SSO provider."
description: |
  This plugin allows users to sign in through an SSO provider (such as Google, Facebook, or your own provider). This enables one-click signin.
  Review documentation at https://github.com/9p4/jellyfin-plugin-sso
category: "Authentication"
artifacts:
  - "SSO-Auth.dll"
  - "IdentityModel.OidcClient.dll"
  - "IdentityModel.dll"
changelog: |
  3.0.0.0: Add more RBAC features and option to unregister user from SSO
  2.0.1.0: Fix improper artifact loading
  2.0.0.0: Add RBAC and Google support
  1.0.0.0: Initial Release
