name: Lint Commit Name

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    name: Validate Commit
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@91682d013dea3ff257520b9b68c9cb93ced4fe9b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
