name: Publish Nightly

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Dotnet
      run: dotnet build --no-restore --warnaserror
    - name: "Flag as nightly in build.yaml"
      uses: fjogeleit/yaml-update-action@v0.10.0
      with:
        valueFile: 'build.yaml'
        propertyPath: 'version'
        value: "0.0.0.9000"
        commitChange: false
        updateFile: true
    - name: "JPRM: Build"
      id: jrpm
      uses: oddstr13/jellyfin-plugin-repository-manager@master
      with:
        version: "0.0.0.9000"
        verbosity: debug
        path: .
        dotnet-target: "net6.0"
        output: _dist
    - name: Publish output artifacts
      id: publish-assets
      uses: softprops/action-gh-release@50195ba7f6f93d1ac97ba8332a178e008ad176aa
      with:
          prerelease: false
          fail_on_unmatched_files: true
          tag_name: nightly
          files: |
            _dist/*
            build.yaml
          body: |
            Nightly build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish Plugin Manifest
      uses: matthewstrasiotto/jellyfin-plugin-repo-action@dev-working
      with:
        ignorePrereleases: false
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        pagesBranch: manifest-release
        pagesFile: manifest.json

